### ISSUE TITLE
Bug slicing a RB into ranges

### ISSUE THREAD

**Issue by ryazwinski** [andreasvc/roaringbitmap#15] opened 2016-10-16 01:22 UTC
In [9]: with open('bug.pickle','rb') as ifile:
   ...:     unp=Unpickler(ifile)
   ...:     d=unp.load()
   ...:

In [10]: len(d)
Out[10]: 544539

In [13]: 544539/4
Out[13]: 136134.75

In [16]: len(d[0:136135])
Out[16]: 136135

In [17]: len(d[136135:136135*2])
Out[17]: 128376

???

Sample data at: https://www.dropbox.com/s/ytwj4fiv786ic6b/bug.pickle?dl=0

**Comment by andreasvc** [comment] 2016-10-21 08:05
Thanks for the report. I believe the issue is fixed now. The code in question is still messier than I'd like it to be, so there might still be edge cases I didn't think of.

**Closed by andreasvc** 2016-10-21 08:05 UTC
